version: '3'

services:
    manager-nginx:
        build:
            context: ./docker/development
            dockerfile: nginx.docker
        volumes:
            - ./:/app
        depends_on:
            - manager-php-fpm
        ports:
            - "8080:80"
    manager-php-fpm:
        build:
            context: ./docker/development
            dockerfile: php-fpm.docker
        environment:
            PHP_IDE_CONFIG: "serverName=local"
        volumes:
            - ./:/app
            - ./docker/development/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini